name: bitsdojo_window_platform_interface
description: A common platform interface for the bitsdojo_window plugin.
homepage: https://github.com/bitsdojo/bitsdojo_window/bitsdojo_window_platform_interface
# NOTE: We strongly prefer non-breaking changes, even at the expense of a
# less-clean API. See https://flutter.dev/go/platform-interface-breaking-changes
version: 0.2.0

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.9.1
  plugin_platform_interface: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
  pedantic: ^1.11.1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"
